### ISSUE TITLE
Run application in docker from unprivileged user

### ISSUE THREAD

**Issue by Nklya** [rrreeeyyy/exporter_proxy#10]
Hello.

According to best practices, it's good to run an application in Docker container from an unprivileged user.

Examples from Prometheus and Grafana:
https://github.com/prometheus/prometheus/blob/master/Dockerfile#L18
https://github.com/grafana/grafana/blob/master/Dockerfile#L83

P.S. I can create PR if needed.

**Comment by rrreeeyyy** [comment]
Thanks for your advice! That makes sense... I created #11 to use `nobody` user in Docker.
